spring.application.name=Chat App Backend
# Configuration du serveur
server.port=8080

# Configuration MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=chatapp

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.chatapp=DEBUG